# author: jaemin.joo
# Legacy CI script for harbor( CD script: ArgoCD)
# Using:
# - docker
# - variables:

statges:
  - image

docker_build:
  tags:
    - Legacy
  only:
    - feat-ci-script
  stage: image
  image: docker:stable
  variables:
    DOCKER_OPTS: "--insecure-registry=$HARBOR_HOST"
  services:
    - docker:dind
  before_script:
    - echo "$HARBOR_HOST" | echo "- $HARBOR_SPRING_USER" | echo "- $HARBOR_SPRING_PASSWORD"
    - echo "$HARBOR_SPRING_PASSWORD" | docker login -u "$HARBOR_SPRING_LOGIN" --password-stdin
  script:
    - docker build -t $APP:$MAIN_VERSION --no-cache .
    - docker tag $APP:$MAIN_VERSION $HARBOR_HOST/$PROJECT/$APP:$MAIN_VERSION
    # latest version ArgoCD에서 확인할 수 있도록 추가
    - docker tag $HARBOR_HOST/$PROJECT/$APP:$MAIN_VERSION $HARBOR_HOST/$PROJECT/$APP:latest
    - docker push $HARBOR_HOST/$PROJECT/$APP:$MAIN_VERSION
    - docker push $HARBOR_HOST/$PROJECT/$APP:latest

