FROM openjdk:11-jre-slim
ARG JAR_FILE_PATH=build/libs/*.jar
ARG APPLICATION_YAML_PATH
ARG DATABASE_DEPLOY_URL
ARG DATABASE_DEPLOY_ID
ARG DATABASE_DEPLOY_PWD
RUN echo ${APPLICATION_YAML_PATH} $APPLICATION_YAML_PATH "$APPLICATION_YAML_PATH"
RUN echo ${DATABASE_DEPLOY_URL} $DATABASE_DEPLOY_URL "$DATABASE_DEPLOY_URL"
RUN echo ${DATABASE_DEPLOY_ID} $DATABASE_DEPLOY_ID "$DATABASE_DEPLOY_ID"
RUN echo ${DATABASE_DEPLOY_PWD} $DATABASE_DEPLOY_PWD "$DATABASE_DEPLOY_PWD"
COPY ${JAR_FILE_PATH} /home/quant/SpringApp.jar
WORKDIR /home/quant
ENTRYPOINT ["java", "-jar","SpringApp.jar","--spring.profiles.active=$APPLICATION_YAML_PATH","--spring.datasource.url=$DATABASE_DEPLOY_URL"]
#ENTRYPOINT ["java", "-jar","SpringApp.jar","-Dspring.profiles.active=${APPLICATION_YAML_PATH}","-Dspring-boot.run.arguments=--DATABASE_DEPLOY_URL=${DATABASE_DEPLOY_URL},--DATABASE_DEPLOY_ID=${DATABASE_DEPLOY_ID},--DATABASE_DEPLOY_PWD=${DATABASE_DEPLOY_PWD}"]